version: '3.3'

services:
  chain:
    container_name: "chain"
    image: fast-updates
    command: bash -c "yarn hardhat node > /dev/null"
    restart: always
    # ports:
    #   - 8545:8545
  setup:
    container_name: "setup"
    image: fast-updates
    command: bash -c "sleep 5 && yarn hardhat chain-config && yarn hardhat deploy-contracts --network docker"
    volumes:
      - "./:/fast-updates/deployment/simulation"
    depends_on:
      - chain
  daemon:
    container_name: "daemon"
    image: fast-updates
    command: bash -c "sleep 35 && yarn hardhat run-admin-daemon --network docker"
    volumes:
      - "./:/fast-updates/deployment/simulation"
    depends_on:
      - chain
    restart: always
  provider1:
    container_name: "provider1"
    image: fast-updates
    command: bash -c "sleep 35 && yarn ts-node deployment/scripts/run-price-voter.ts 1"
    volumes:
      - "./:/fast-updates/deployment/simulation"
    depends_on:
      - chain
    restart: always
  provider2:
    container_name: "provider2"
    image: fast-updates
    command: bash -c "sleep 35 && yarn ts-node deployment/scripts/run-price-voter.ts 2"
    volumes:
      - "./:/fast-updates/deployment/simulation"
    depends_on:
      - chain
    restart: always
  provider3:
    container_name: "provider3"
    image: fast-updates
    command: bash -c "sleep 35 && yarn ts-node deployment/scripts/run-price-voter.ts 3"
    volumes:
      - "./:/fast-updates/deployment/simulation"
    depends_on:
      - chain
    restart: always
  provider4:
    container_name: "provider4"
    image: fast-updates
    command: bash -c "sleep 35 && yarn ts-node deployment/scripts/run-price-voter.ts 4"
    volumes:
      - "./:/fast-updates/deployment/simulation"
    depends_on:
      - chain
    restart: always
  provider5:
    container_name: "provider5"
    image: fast-updates
    command: bash -c "sleep 35 && yarn ts-node deployment/scripts/run-price-voter.ts 5"
    volumes:
      - "./:/fast-updates/deployment/simulation"
    depends_on:
      - chain
    restart: always
  provider6:
    container_name: "provider6"
    image: fast-updates
    command: bash -c "sleep 35 && yarn ts-node deployment/scripts/run-price-voter.ts 6"
    volumes:
      - "./:/fast-updates/deployment/simulation"
    depends_on:
      - chain
    restart: always
  provider7:
    container_name: "provider7"
    image: fast-updates
    command: bash -c "sleep 35 && yarn ts-node deployment/scripts/run-price-voter.ts 7"
    volumes:
      - "./:/fast-updates/deployment/simulation"
    depends_on:
      - chain
    restart: always
  provider8:
    container_name: "provider8"
    image: fast-updates
    command: bash -c "sleep 35 && yarn ts-node deployment/scripts/run-price-voter.ts 8"
    volumes:
      - "./:/fast-updates/deployment/simulation"
    depends_on:
      - chain
    restart: always
  provider9:
    container_name: "provider9"
    image: fast-updates
    command: bash -c "sleep 35 && yarn ts-node deployment/scripts/run-price-voter.ts 9"
    volumes:
      - "./:/fast-updates/deployment/simulation"
    depends_on:
      - chain
    restart: always





